# Intro to Numpy

In [1]:
import numpy as np


In [2]:
myarr = np.array([[1,2,3,888]])

In [3]:
myarr.shape

(1, 4)

# Array creation method 
**Creates an array from a list or tuple.**

In [4]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
listarr.shape

(3, 3)

In [7]:
listarr.dtype

dtype('int64')

In [8]:
listarr.size

9

In [9]:
tupplearr = np.array((4, 5, 6))

In [10]:
tupplearr

array([4, 5, 6])

#### **intrinsic numpy array creation object**

In [11]:
zero = np.zeros((2,5))

In [12]:
rng = np.arange(10)

In [13]:
lspace = np.linspace(1,10,5)

In [14]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
emp = np.empty((3,3))

In [16]:
emp

array([[1.36313606e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [17]:
emp_like = np.empty_like(lspace)

In [18]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
idn = np.identity(3)

In [20]:
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Two impt function ***reshape & ravel***

In [21]:
arr = np.arange(10)

In [22]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])