<a href="https://colab.research.google.com/github/Ayushpal2006/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY IMPORT

In [ ]:
import numpy as np

ARRAY CREATION 1D AND 2D

In [ ]:
arr=np.array([1,2,8,4])
matrix=np.array([[1,3],[5,9]])

In [ ]:
print(arr)
print(matrix)

[1 2 8 4]
[[1 3]
 [5 9]]


Shape,size,datatype and dimension

In [ ]:
print(arr.shape,arr.size,arr.dtype,arr.ndim)

(4,) 4 int64 1


In [ ]:
print(matrix.shape,matrix.size,matrix.dtype,matrix.ndim)

(2, 2) 4 int64 2


Zero matrix of order m x n

In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


 matrix with only 1 as element

In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


full matrix of order m x n with single element

In [ ]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


 identity matrix

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


martrix with random elements ranging 0 to 1

In [ ]:
print(np.random.rand(2,3))

[[0.65512269 0.38212437 0.71857242]
 [0.8726219  0.78019975 0.89966469]]


matrix element in defined range

 element greater than or less than or boolean indexing

In [ ]:
arr[arr>1]

array([2, 8, 4])

sorting

In [ ]:
np.sort(arr)

array([1, 2, 4, 8])

In [ ]:
np.sort(matrix)

array([[1, 3],
       [5, 9]])

indexing

In [ ]:
print(arr[2])

8


slicing

In [ ]:
print(arr[1:3])

[2 8]


array operation

In [ ]:
arr_1=arr+5
print(arr_1+6) #broadcasting
print(arr+arr_1)

[12 13 19 15]
[ 7  9 21 13]


array mathematical operation

In [ ]:
#common function
print(np.sum(arr),np.mean(arr),np.min(arr),np.max(arr))
print(np.sum(matrix),np.mean(matrix),np.min(matrix),np.max(matrix))

15 3.75 1 8
18 4.5 1 9


In [ ]:
#trigonomatric function
print(np.sin(arr))

[ 0.84147098  0.90929743  0.98935825 -0.7568025 ]


In [ ]:
#linear algebra
print(np.linalg.det(matrix)) #determinant

-6.0


reshaping and transpose

In [ ]:
reshape=arr.reshape(2,2)
print(matrix.T)
print(reshape)

[[1 5]
 [3 9]]
[[1 2]
 [8 4]]


# ARRAY advance op

In [ ]:
arre=([1,1,2,2,8,3,9])
print(np.sort(arre)) #sort
print(np.unique(arre)) #unique element
print(np.where(arr >= 3,'Greater','Smaller')) #condition

[1 1 2 2 3 8 9]
[1 2 3 8 9]
['Smaller' 'Smaller' 'Greater' 'Greater']


File I/O with numpy

In [ ]:
np.save('array.npy',arr) #saving array
load = np.load('array.npy') # load array
print(load)
np.savetxt('array.txt',arr) # saving as txt

[1 2 8 4]


Concatination and spliting

In [ ]:
print(np.concatenate((arr,arre))) #concatenate
print(np.array_split(arre,3)) #split

[1 2 8 4 1 1 2 2 8 3 9]
[array([1, 1, 2]), array([2, 8]), array([3, 9])]


Performance Features

Arange and range

In [ ]:
data=np.arange(0,20,5.2) #arrange
print(data)
for data_1 in range(0,20,5): #simple range function in python
    print(data_1)
data_2=np.array(range(0,20,5)) #array with range function
print(data_2)

[ 0.   5.2 10.4 15.6]
0
5
10
15
[ 0  5 10 15]


Differance between arrange and range

USES

# MATRICES

In [ ]:
print(matrix*reshape)# element wise multiplication
print("\n",matrix@reshape)#dot product or matrix product
print("\n",matrix)
print("\n",reshape)
print("\n",matrix.T) #transpose
print("\n", np.linalg.det(reshape))#determinant
print("\n",np.linalg.inv(matrix))#inverse
print("\n",np.linalg.matrix_rank(matrix))#rank

[[ 1  6]
 [40 36]]

 [[25 14]
 [77 46]]

 [[1 3]
 [5 9]]

 [[1 2]
 [8 4]]

 [[1 5]
 [3 9]]

 -11.999999999999995

 [[-1.5         0.5       ]
 [ 0.83333333 -0.16666667]]

 2


Lenear Algebra

In [ ]:
values, vectors = np.linalg.eig(matrix)
print("Eigenvalues:", values)
print("Eigenvectors:", vectors)


Eigenvalues: [-0.56776436 10.56776436]
Eigenvectors: [[-0.88627607 -0.29919012]
 [ 0.46315735 -0.95419352]]


In [ ]:
A = np.array([[2, 1], [1, 3]])
B = np.array([8, 18])
print( "X =",np.linalg.solve(A, B))# solve for matrix x

X = [1.2 5.6]


In [ ]:
print(np.trace(A))#trace
print(A.flatten())#change dimenssion to 1D
print(B.reshape(2, 1))  # reshaping matrix

5
[2 1 1 3]
[[ 8]
 [18]]


# NUMPY Questions

In [ ]:
#output of the function
a1 = np.zeros((2,3))
print(a1)
a2 = np.array([[3,4,5],[7,8,9]])
print(a1+a2)
a1=np.append(a1,a2,axis=0)
print(a1)
print('shape of array',a1.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
[[3. 4. 5.]
 [7. 8. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [3. 4. 5.]
 [7. 8. 9.]]
shape of array (4, 3)


In [ ]:
marks=np.random.randint(60,100,(3,2))
student=np.array([['student_1','student_2']])
marksheet=np.append(student,marks,axis=0)
print(marksheet)
print('\n','dimenssion of marksheet =',marksheet.ndim)
print('\n','shape of marksheet =',marksheet.shape)
print('\n','data type of marksheet =',marksheet.dtype)

[['student_1' 'student_2']
 ['85' '95']
 ['94' '90']
 ['97' '89']]

 dimenssion of marksheet = 2

 shape of marksheet = (4, 2)

 data type of marksheet = <U21


In [ ]:
b1=np.arange(6)
b2=np.array([[1,2,3],[4,5,6]])
print(b1[1],b2[1],'\n',b1)
print('\n',b1[:3],b2[::-1])


1 [4 5 6] 
 [0 1 2 3 4 5]

 [0 1 2] [[4 5 6]
 [1 2 3]]


In [ ]:
narr=np.array([-4.6,8.2,14.5,56.9,29.4,-72.7])
narr1=narr.astype(np.int_)
print(narr1)

[ -4   8  14  56  29 -72]


In [ ]:
arr_x=np.array([[1,2,3],[4,5,6]])
arr_y=np.array([[3,5,7],[2,4,6]])
print(arr_x.dtype)
print(arr_y>arr_x)

int64
[[ True  True  True]
 [False False False]]


In [ ]:
array = np.array([1, 2, 3, 4, 1.5, 0.5, 2.5])
print(array[array>2])

[3.  4.  2.5]


In [ ]:
a=np.arange(16).reshape(4,4)
print(a)
a[a>7]=-1
print('\n',a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
arr1 =np.array([[[3,-7],[9,2]],[[-15,4],[1,2]]])
arr2 = np.ones_like(arr1)
print(arr2)
print('\n',arr1[arr1<2])
print('\n',arr1[::2])#start:stop:step
print('\n',arr1.ndim)
print('\n',arr1.dtype)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]

 [ -7 -15   1]

 [[[ 3 -7]
  [ 9  2]]]

 3

 int64


In [ ]:
names = np.array(['ram','raj','rahim','shamshi','gourav','raj','raj'])
data = np.arange(14).reshape(7,2)
print(data.T)
result=data[names!='raj',:1]
print(data)
print(result[2:])
result

[[ 0  2  4  6  8 10 12]
 [ 1  3  5  7  9 11 13]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[6]
 [8]]


array([[0],
       [4],
       [6],
       [8]])

In [ ]:
print(data[[-2,-4,-7]]) #row printing

[[10 11]
 [ 6  7]
 [ 0  1]]


In [ ]:
print(data[[1,5,2],[0,0,1]]) #element printing

[ 2 10  5]


In [ ]:
d1=data[2:7:1]=2
print(data)
d1

[[0 1]
 [2 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


2

# INDEXING AND SLICING

In [ ]:
arr_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3D=np.arange(16).reshape(2,2,4)
print(arr_2D[0])
arr_2D[0]=4
print(arr_2D)
print(arr_2D[1,1])
print(arr_3D)
print('\n',arr_3D[0])
arr_3D[0]=1
arr_3D

[1 2 3]
[[4 4 4]
 [4 5 6]
 [7 8 9]]
5
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

 [[0 1 2 3]
 [4 5 6 7]]


array([[[ 1,  1,  1,  1],
        [ 1,  1,  1,  1]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
print(arr_2D[:2])
lower_dim=arr_2D[1:,1:]
print(lower_dim,lower_dim.shape)

[[4 4 4]
 [4 5 6]]
[[5 6]
 [8 9]] (2, 2)


In [ ]:
names = np.array(['ram','raj','rahim','shamshi','gourav','raj','raj'])
data = np.arange(14).reshape(7,2)
print(data)
print(data[names!='raj'])#boolean inexing
print(data[names!='raj',:1])

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[0 1]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [4]
 [6]
 [8]]


In [ ]:
arr_fa=np.zeros((8,8))
for i in range(8):
    arr_fa[i]=i
print(arr_fa.astype(int))
print('\n',arr_fa[[4,5,6,0],[2,1,0,3]].astype(int))
print('\n',arr_fa[[4,5,6,0]][:,[2,1,0,3]].astype(int))
arr_fa[[4,5,6,0],[2,1,0,3]]=9
print('\n',arr_fa.astype(int))
arr_fa=arr_fa.swapaxes(0,1) #transpose can be use with function swapaxes function
for i in range(8):
    arr_fa[i,i]=5
print('\n',arr_fa.astype(int))

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7]]

 [4 5 6 0]

 [[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [0 0 0 0]]

 [[0 0 0 9 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 9 4 4 4 4 4]
 [5 9 5 5 5 5 5 5]
 [9 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7]]

 [[5 1 2 3 4 5 9 7]
 [0 5 2 3 4 9 6 7]
 [0 1 5 3 9 5 6 7]
 [9 1 2 5 4 5 6 7]
 [0 1 2 3 5 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 5 7]
 [0 1 2 3 4 5 6 5]]


# Pseudonumber Generation

In [ ]:
sam=np.random.standard_normal((4,4))
sam1=np.random.randint(1,100,(2,3))
print(sam)
print(sam1)

[[-0.83636353  2.03842768 -1.1682877   0.40161234]
 [-0.56711377 -0.99796877 -0.43470595  1.46230908]
 [-0.02525291 -0.22214412 -0.62161967 -1.43949062]
 [ 0.65372424 -0.22769335 -2.27682792 -0.0390148 ]]
[[90 40 28]
 [27 69  6]]


In [ ]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)


832 ms ± 277 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
34.8 ms ± 9.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
rng = np.random.default_rng(seed=12345)
sam2 = rng.standard_normal((2, 3))
print(sam2)
type(rng)

[[-1.42382504  1.26372846 -0.87066174]
 [-0.25917323 -0.07534331 -0.74088465]]


numpy.random._generator.Generator

# Numpy advance question


In [ ]:
numx = np.array([[4,3],[2,1]])
numy = np.zeros_like(numx)
print(numy)
z=np.eye(2)*numx
print(z.astype(int))
print((np.eye(2)@numx).astype(int))

[[0 0]
 [0 0]]
[[4 0]
 [0 1]]
[[4 3]
 [2 1]]


In [ ]:
ad1=np.array([[1,1,0],[9,7,8],[6,8,4]])
ad2=np.array([[[5,2,1],[2,1,8]],[[1,2,3],[4,5,6]]])
print(ad1[:2,-1])#[row:column]
print(ad1,'\n')
ad2

[0 8]
[[1 1 0]
 [9 7 8]
 [6 8 4]] 



array([[[5, 2, 1],
        [2, 1, 8]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
print(ad1[:,:2])
ad1[-1,:]

[[1 1]
 [9 7]
 [6 8]]


array([6, 8, 4])

In [ ]:
x1=[32,21,65,89,33,23,22,40,21,32,56,45,44,38,52]
x2=np.array(x1).reshape(5,3)
print(np.mean(x2),np.var(x2),np.median(x2),x2.ndim)
print(np.mean(x1),np.var(x1),np.median(x1))
for i in range(5):
    print('mean,median,variance of row',i+1,np.mean(x2[i]),',',np.var(x2[i]),',',np.median(x2[i]))
x2

40.86666666666667 331.44888888888886 38.0 2
40.86666666666667 331.44888888888886 38.0
mean,median,variance of row 1 39.333333333333336 , 349.5555555555555 , 32.0
mean,median,variance of row 2 48.333333333333336 , 843.5555555555555 , 33.0
mean,median,variance of row 3 27.666666666666668 , 76.22222222222221 , 22.0
mean,median,variance of row 4 44.333333333333336 , 96.22222222222223 , 45.0
mean,median,variance of row 5 44.666666666666664 , 32.88888888888889 , 44.0


array([[32, 21, 65],
       [89, 33, 23],
       [22, 40, 21],
       [32, 56, 45],
       [44, 38, 52]])

In [ ]:
#for culumatve sum of x2
for i in range(5):
    cumulativesum=np.cumsum(x2[i])
    print(cumulativesum)

[ 32  53 118]
[ 89 122 145]
[22 62 83]
[ 32  88 133]
[ 44  82 134]


In [ ]:
x2[:,[0,1]]=x2[:,[1,0]]
x2

array([[21, 32, 65],
       [33, 89, 23],
       [40, 22, 21],
       [56, 32, 45],
       [38, 44, 52]])

In [ ]:
x2[:,0]=np.sort(x2[:,0])
x2[:,1]=np.sort(x2[:,1])
x2[:,2]=np.sort(x2[:,2])
x2

array([[21, 22, 21],
       [33, 32, 23],
       [38, 32, 45],
       [40, 44, 52],
       [56, 89, 65]])

In [ ]:
r=np.where(x2>40,0,x2)
r

array([[21, 22, 21],
       [33, 32, 23],
       [38, 32,  0],
       [40,  0,  0],
       [ 0,  0,  0]])

In [ ]:
x2[x2>40]=0
x2

array([[21, 22, 21],
       [33, 32, 23],
       [38, 32,  0],
       [40,  0,  0],
       [ 0,  0,  0]])

In [ ]:
ad3=np.linspace(0,1,50)
np.round(ad3,4)

array([0.    , 0.0204, 0.0408, 0.0612, 0.0816, 0.102 , 0.1224, 0.1429,
       0.1633, 0.1837, 0.2041, 0.2245, 0.2449, 0.2653, 0.2857, 0.3061,
       0.3265, 0.3469, 0.3673, 0.3878, 0.4082, 0.4286, 0.449 , 0.4694,
       0.4898, 0.5102, 0.5306, 0.551 , 0.5714, 0.5918, 0.6122, 0.6327,
       0.6531, 0.6735, 0.6939, 0.7143, 0.7347, 0.7551, 0.7755, 0.7959,
       0.8163, 0.8367, 0.8571, 0.8776, 0.898 , 0.9184, 0.9388, 0.9592,
       0.9796, 1.    ])

In [ ]:
ad4=np.array([[4,3,2],[1,9,6]])
print(ad4[:2,-1])


[2 6]


In [ ]:
ad5=np.arange(24).reshape(6,4)
print(ad5)
print(ad5[[1,3,5,2],[3,1,0,3]])
print('\n',ad5[[0,2,4]])
print('\n',ad5[[-5,-3,-1]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[ 7 13 20 11]

 [[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]

 [[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]]


In [ ]:
ad6=np.arange(31,47)
ad7=ad6.astype(float).reshape(4,4)
print(ad7)
for i in range(4):
    ad7[i][i]=0
print('\n',ad7)
print('\n',np.ones_like(ad7))

[[31. 32. 33. 34.]
 [35. 36. 37. 38.]
 [39. 40. 41. 42.]
 [43. 44. 45. 46.]]

 [[ 0. 32. 33. 34.]
 [35.  0. 37. 38.]
 [39. 40.  0. 42.]
 [43. 44. 45.  0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
mat=np.array([[[-1,2],[3,4]],[[-5,6],[7,8]]]).astype(float)
print(mat[mat>6])
print(mat.dtype)
print(mat*25)
mat

[7. 8.]
float64
[[[ -25.   50.]
  [  75.  100.]]

 [[-125.  150.]
  [ 175.  200.]]]


array([[[-1.,  2.],
        [ 3.,  4.]],

       [[-5.,  6.],
        [ 7.,  8.]]])

In [ ]:
ad9=np.zeros((2,3))
print(ad9)
ad9[0:]=[1,2,3]
ad9[1:]=[4,5,6]
ad9

[[0. 0. 0.]
 [0. 0. 0.]]


array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
ad10=np.arange(1,18,2).reshape(3,3).T
ad11=np.random.rand(3,2)
print(ad11,'\n'*2,ad10)

[[0.10673086 0.37031881]
 [0.49717466 0.88574331]
 [0.8002147  0.01529956]] 

 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
