<a href="https://colab.research.google.com/github/Ayushpal2006/Numpy/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[2]

np.int64(3)

In [7]:
a[3] = 13

In [8]:
a

array([ 1,  2,  3, 13,  5,  6])

In [9]:
b = a[:2]
b

array([1, 2])

In [10]:
b

array([1, 2])

In [11]:
b[1]

np.int64(2)

In [12]:
a[3:]

array([13,  5,  6])

In [13]:
a[4:]

array([5, 6])

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
a.ndim

2

In [17]:
a = np.array(23)
a
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  0
Shape -  ()
Len of Shape -  0
Size -  1


In [18]:
a = np.array([1, 2])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  1
Shape -  (2,)
Len of Shape -  1
Size -  2


In [19]:
a = np.array([1, 2, 3])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  1
Shape -  (3,)
Len of Shape -  1
Size -  3


In [20]:
a = np.array([[1, 2],
              [1, 2]])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  2
Shape -  (2, 2)
Len of Shape -  2
Size -  4


In [21]:
a = np.array([[1, 2, 6, 7],
              [1, 2, 6, 7]])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  2
Shape -  (2, 4)
Len of Shape -  2
Size -  8


In [23]:
a = np.array([
                [[1, 2, 6],
                [1, 2, 6]],

                [[1, 2, 5],
                [1, 2, 4]]
])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  3
Shape -  (2, 2, 3)
Len of Shape -  3
Size -  12


In [24]:
a = np.array([[
                [[1, 2, 6],
                [1, 2, 6]],

                [[1, 2, 5],
                [1, 2, 4]]
            ],
             [
                [[1, 2, 6],
                [1, 2, 6]],

                [[1, 2, 5],
                [1, 2, 4]]
            ]]
            )
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  4
Shape -  (2, 2, 2, 3)
Len of Shape -  4
Size -  24


In [25]:
a.dtype

dtype('int64')

In [26]:
np.zeros(2)

array([0., 0.])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((2,3,7, 4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0.

In [29]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [30]:
np.ones((6, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [32]:
np.empty((3, 8))

array([[    nan,     nan, 0.e+000,     nan, 5.e-324,     nan, 1.e-323,
            nan],
       [5.e-324, 0.e+000, 1.e-323, 5.e-324, 5.e-324, 1.e-323, 0.e+000,
        5.e-324],
       [    nan, 1.e-323,     nan, 5.e-324,     nan, 0.e+000,     nan,
            nan]])

In [33]:
np.arange(2, 10, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [34]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [35]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [36]:
x = np.zeros(2, dtype=np.int64)
x

array([0, 0])

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr = np.array([30, 10, 20])
np.argsort(arr)

array([1, 2, 0])

In [43]:
arr = np.array([90, 98, 23, 89, 12, 43, 76])
np.partition(arr, 2)

array([12, 23, 43, 76, 89, 90, 98])

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a+b

array([ 6,  8, 10, 12])

In [49]:
x = np.array([[1, 2], [3, 4]])
x
y = np.array([[5, 6]])
y
z = np.array([[8,9]])
z
np.concatenate((x, y, z), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [50]:
a = np.arange(2, 10, 2)

In [51]:
a

array([2, 4, 6, 8])

In [52]:
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

In [53]:
a = np.arange(1, 7)

In [54]:
a

array([1, 2, 3, 4, 5, 6])

In [55]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [58]:
np.reshape(arr, (3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
np.reshape(arr, (2, 3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [61]:
arr = np.arange(6)
np.reshape(arr, (3,2))
np.reshape(arr, (2,3), order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [63]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [66]:
a.ndim

1

In [67]:
a2.ndim

2

In [68]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [69]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [70]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [71]:
arr = np.array([12, 89, 45])

In [72]:
arr[1:]

array([89, 45])

In [73]:
arr[2:]

array([45])

In [74]:
arr[2]

np.int64(45)

In [75]:
arr[3:]

array([], dtype=int64)

In [76]:
arr[-2]

np.int64(89)

In [77]:
arr[-2:]

array([89, 45])

In [78]:
arr[:-1]

array([12, 89])

In [81]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
a < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [83]:
a[a<6]

array([1, 2, 3, 4, 5])

In [84]:
a = np.array([[13 , 62, 3, 42], [75, 6, 7, 84], [93, 10, 2, 12]])

In [85]:
a<7

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [90]:
a[(a<7) | (a>75)]

array([ 3,  6, 84, 93,  2])

In [91]:
np.nonzero((a<7) | (a>75))

(array([0, 1, 1, 2, 2]), array([2, 1, 3, 0, 2]))

In [92]:
a1 = np.array([[1, 1, 3],
               [2, 2, 4]])

a2 = np.array([[3, 3, 6],
               [4, 4, 7]])

In [94]:
np.vstack((a1, a2))

array([[1, 1, 3],
       [2, 2, 4],
       [3, 3, 6],
       [4, 4, 7]])

In [95]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [100]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [101]:
np.hsplit(x, (3, 4, 7, 8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8],
        [20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [102]:
arr = np.arange(6)

In [103]:
b = arr

In [104]:
print(arr)
print(b)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [105]:
b[2] = 10

In [106]:
print(arr)
print(b)

[ 0  1 10  3  4  5]
[ 0  1 10  3  4  5]


In [107]:
arr = np.arange(6)

In [108]:
arr

array([0, 1, 2, 3, 4, 5])

In [109]:
b = arr[2:4]

In [110]:
b

array([2, 3])

In [111]:
b[1] = 20

In [112]:
arr

array([ 0,  1,  2, 20,  4,  5])

In [113]:
arr = np.arange(6)
b = arr.copy()

In [114]:
b[2] = 20

In [120]:
print(arr)
print(b)

[0 1 2 3 4 5]
[ 5  6  7  8  9 10 11 12 13 14]


In [121]:
a = np.arange(2, 10)
b = np.arange(5, 15)
print(a)
print(b)

[2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [122]:
a+b

ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [123]:
a - b

ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [124]:
a * b

ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [125]:
a / b

ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [126]:
a.sum()

np.int64(44)

In [127]:
a = np.arange(1, 10)
b = np.arange(1, 10)
print(a)
print(b)
print(a.sum())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
45


In [128]:
b = a.reshape(3,3)

In [129]:
b.sum(axis = 0)

array([12, 15, 18])

In [130]:
a = np.arange(1, 10).reshape(3,3)
print(a)
a.sum(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [131]:
a.sum(axis = 1)

array([ 6, 15, 24])

In [132]:
a.max()

np.int64(9)

In [133]:
a.min()

np.int64(1)

In [134]:
a.max(axis = 0)

array([7, 8, 9])

In [135]:
a.min(axis = 1)

array([1, 4, 7])

In [136]:
a.prod(axis = 1)

array([  6, 120, 504])

In [137]:
a.mean(axis = 1)

array([2., 5., 8.])

In [138]:
a.std()

np.float64(2.581988897471611)

In [139]:
np.random.randint(2, 9, (3, 2))

array([[4, 8],
       [3, 3],
       [3, 6]])

In [140]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[3, 0, 1, 0],
       [3, 2, 3, 1]])

In [141]:
arr = rng.integers(2, 9, (3, 2))

In [142]:
arr

array([[6, 2],
       [8, 6],
       [6, 3]])

In [143]:
arr.T

array([[6, 8, 6],
       [2, 6, 3]])

In [144]:
arr.transpose()

array([[6, 8, 6],
       [2, 6, 3]])

In [145]:
arr

array([[6, 2],
       [8, 6],
       [6, 3]])

In [146]:
arr.transpose()

array([[6, 8, 6],
       [2, 6, 3]])

In [147]:
arr

array([[6, 2],
       [8, 6],
       [6, 3]])

In [148]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [149]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [150]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [152]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [153]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [154]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [156]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


In [157]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

