In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [3]:
arr.sum()

45

In [4]:
arr.sum(axis = 1)

array([ 6, 15, 24])

In [5]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
arr.flat

In [7]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [8]:
arr.ndim

2

In [9]:
one  = np.array([1,3,4,643,2])

In [10]:
one.argmax()

3

In [11]:
one.argsort()

array([0, 4, 1, 2, 3])

In [12]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2 = np.identity(3)

In [14]:
arr+arr2

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [15]:
arr*arr2

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [16]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [17]:
np.where(arr>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [21]:
np.count_nonzero(arr)

9

In [22]:
np.count_nonzero(arr2 == 1)

3

In [24]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))